- platform: foscam
  ip: !secret foscam_ip
  username: !secret foscam_username
  password: !secret foscam_password
  name: SophiaCam
- platform: generic
  still_image_url: https://cdn.knmi.nl/knmi/map/general/weather-map.gif?b86e9c80abac3fec623abb892b293b87
  name: Weerkaart NL
- platform: mjpeg
  mjpeg_url: !secret mjpeg_url
  name: KoiCam
  username: !secret mjpeg_user
  password: !secret mjpeg_pass